language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fdsasa/docker-react -f Dockerfile.dev .

# CI=true https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash
script:
  - docker run -e CI=true fdsasa/docker-react npm run test